# Introduction to Data Science 2026

# Week 1

## Exercise 1 | Matrix warm-up
<span style="background-color: #ccfff2"> *Note: You can find tutorials for NumPy and Pandas under 'Useful tutorials' in the course material.*</span>

One of the most useful properties of any scientific programming language (Python with NumPy, R, Julia, etc) is that they allow us to work with matrices efficiently. Let's learn more about these features!

### 1.1 Basics

1. Let's start by creating two arrays <span style="background-color: #ccfff2"> A</span> and <span style="background-color: #ccfff2"> B</span> which each have the integers <span style="background-color: #ccfff2"> 0, 1, 2, ..., 1e7-1</span>. Use the normal arrays or lists of the programming language you are using, e.g. *list* or *[ ]* or *numpy.array()* in Python.

In [185]:
import numpy as np

a = np.arange(0,10000000)
b = np.arange(0,10000000)

print(a)

[      0       1       2 ... 9999997 9999998 9999999]


2. Create a function that uses a <span style="background-color: #ccfff2"> for loop</span> or equivalent to return a new array <span style="background-color: #ccfff2"> C</span>, which contains the <span style="background-color: #ccfff2"> element-wise sum of *A* and *B*</span>, e.g. C should contain the integers <span style="background-color: #ccfff2"> 0, 2, 4, etc</span>.

In [213]:
def add_with_for(A,B):
    C = []
    for i in range(len(A)):
        x = A[i] + B[i]
        C.append(x)
    return C

result = add_with_for(a,b)
print(result[:10])

[np.int64(0), np.int64(2), np.int64(4), np.int64(6), np.int64(8), np.int64(10), np.int64(12), np.int64(14), np.int64(16), np.int64(18)]


3. Next, let's create another function that uses NumPy (or equivalent) to do the same. To try it out, allocate two arrays (e.g. using <span style="background-color: #ccfff2"> np.array</span> in NumPy) and add the arrays together using your function. Don't use loops, instead, find out how to add the two arrays directly. What do you notice in comparison to the previous function?

In [187]:
def add_with_numpy(a,b):
    c = np.add(a,b)
    return c

add_with_numpy(a,b)

array([       0,        2,        4, ..., 19999994, 19999996, 19999998],
      shape=(10000000,))

### 1.2 Array manipulation

<span style="background-color: #ccfff2"> *Note: for the following exercises, only use NumPy or equivalent functions. Don't use any loops.* </span>
1. Create the following array:

*[hint: <span style="background-color: #ccfff2"> np.reshape</span>]*

In [188]:
# array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
#        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
#        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
#        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
#        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
#        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
#        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
#        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
#        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
#        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])


In [189]:
x = np.arange(100).reshape((10, 10))
print(x)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


2. Create the following array:

In [190]:
# array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

In [191]:
x = np.array([0., 1.] * 5)
x = np.tile(x, (10,1))
    
print(x)


[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]]


3. Create the following array (D):

In [192]:
# array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

In [193]:
d = np.ones((10,10))
np.fill_diagonal(d,0)
print(d)

[[0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]]


4. Create the following array (E):

In [194]:
# array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [195]:
e = np.ones((10,10))
np.fill_diagonal(np.fliplr(e), 0)

print(e)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5. Call the last two matrices <span style="background-color: #ccfff2">D</span> and <span style="background-color: #ccfff2">E</span>, respectively. Show that the determinant of their product (matrix multiplication) is the same as the product of their determinants. That is calculate both <span style="background-color: #ccfff2">det(DE)</span> and <span style="background-color: #ccfff2">det(D) * det(E)</span>, and show that they are the same. Is it a coincidence? (I think not) The product of the determinants (or the determinant of the product) should be -81.

In [196]:
det_e = np.linalg.det(e)
det_d = np.linalg.det(d)
print(det_e*det_d)

y = np.linalg.det(np.dot(e,d))
print(y)

-81.0
-81.0000000000001


It is not a coincidence, but a [rule](https://en.wikipedia.org/wiki/Determinant#By_multiplicative_property). 

### 1.3 Slicing

Array slicing is a powerful way to extract data from an array. Let's practice array slicing with the following exercises!

1. Load the [California housing dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html). The data should be a matrix of shape <span style="background-color: #ccfff2">(20640, 8)</span>, that is 20640 rows and 8 columns. Use the <span style="background-color: #ccfff2">.shape</span> attribute of NumPy arrays to verify this. Here's a [description of the fields](https://scikit-learn.org/stable/datasets/real_world.html#california-housing-dataset).

In [197]:
from sklearn.datasets import fetch_california_housing
import pandas as pd

housing = fetch_california_housing(as_frame=True)
df = housing.frame
print(housing.data.shape)
print(df.head())



(20640, 8)
   MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  MedHouseVal  
0    -122.23        4.526  
1    -122.22        3.585  
2    -122.24        3.521  
3    -122.25        3.413  
4    -122.25        3.422  


2. Select rows where the average number of bedrooms <span style="background-color: #ccfff2">(AveBedrms)</span> is higher than 2. The first few row indices should be <span style="background-color: #ccfff2">710,  1023,  1024, ...</span> (zero-indexed). Count these houses - how many rows are selected? *[hint: <span style="background-color: #ccfff2">np.where</span>]*

In [198]:
print(df.loc[df['AveBedrms'] > 2])

       MedInc  HouseAge   AveRooms  AveBedrms  Population  AveOccup  Latitude  \
710    2.4196      26.0   8.518248   2.700730       253.0  1.846715     37.68   
1023   2.2417      15.0  10.515306   2.372449       573.0  2.923469     38.72   
1024   3.1500      16.0  29.852941   5.323529       202.0  1.980392     38.52   
1030   3.0125      15.0  10.168591   2.057737      1103.0  2.547344     38.55   
1102   2.4028      17.0  31.777778   9.703704        47.0  1.740741     40.06   
...       ...       ...        ...        ...         ...       ...       ...   
20093  2.0625      37.0  24.669118   4.897059       338.0  2.485294     38.12   
20094  2.1250      26.0  37.063492   7.185185       416.0  2.201058     38.19   
20110  3.2589       9.0  11.458508   2.056161      2811.0  2.356245     37.84   
20112  4.0833      18.0  11.536585   2.804878        88.0  2.146341     37.85   
20113  3.4861      17.0  17.300000   6.500000        51.0  2.550000     37.94   

       Longitude  MedHouseV

3. Select the rows where the median house age (i.e. median in each block group) <span style="background-color: #ccfff2">(HouseAge)</span> is between 1 and 3 years (inclusive). There should be **124** of these.

In [199]:
print(df[(df['HouseAge'] >= 1) & (df['HouseAge' ] <= 3 )])

       MedInc  HouseAge   AveRooms  AveBedrms  Population  AveOccup  Latitude  \
59     2.5625       2.0   2.771930   0.754386        94.0  1.649123     37.82   
854    2.8750       2.0   5.624161   1.979866       240.0  1.610738     37.59   
871    6.0824       3.0   5.090447   1.039230      7205.0  2.617145     37.52   
959    4.4087       3.0   5.385965   1.276316       793.0  1.739035     37.70   
976    2.1187       3.0   3.394794   1.006508       769.0  1.668113     37.66   
...       ...       ...        ...        ...         ...       ...       ...   
19536  4.2500       1.0  20.125000   2.928571       402.0  3.589286     37.65   
19561  4.6484       2.0   6.406607   1.059720      2784.0  3.537484     37.59   
19650  2.6103       2.0   7.308594   1.597656       707.0  2.761719     37.52   
20070  2.4191       3.0   6.274194   1.645161       422.0  2.268817     37.99   
20367  8.0428       3.0   8.239437   1.042254       493.0  3.471831     34.16   

       Longitude  MedHouseV

4. Find the mean of the block group population <span style="background-color: #ccfff2">(Population)</span> for homes whose median value is more than 25000 USD (the target variable). It should be around **1425.68**.

In [200]:
new_df = df.loc[df['MedHouseVal'] > 0.25000]

print(new_df['Population'].mean())



1425.6833737275813


## Exercise 2 | Working with text data

Next, let's look into some text data. We will be looking into Amazon reviews, and the necessary steps to transform a raw dataset into a format more suitable for prediction tasks.

1. Download the automotive 5-core dataset from [here](https://mcauleylab.ucsd.edu/public_datasets/data/amazon_v2/categoryFilesSmall/Automotive_5.json.gz). Next, you can extract the data in <span style="background-color: #ccfff2">JSON</span> format. You can also download one of the bigger ones, if you are feeling ambitious. Open the JSON file. Access the <span style="background-color: #ccfff2">reviewText</span> field, which contains the unstructured review text written by the user.

For instance, the first review reads as follows: 

*'After I wrote the below review, the manufacturer contacted me and explained how to use this.  Instead of the (current) picture on Amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally. [...]'*

In [217]:
df = pd.read_json('Automotive_5.json', lines=True)
df.head()


,overall,verified,reviewTime,reviewerID,asin,style,reviewerName,reviewText,summary,unixReviewTime,vote,image
0,4,False,"05 1, 2015",A8WEXFRWX1ZHH,0209688726,{'Color:': ' AC'},Goldengate,"After I wrote the below review, the manufactur...",Works well if you place phone in horizontally ...,1430438400,NaN,NaN
1,1,True,"04 19, 2018",ABCA1A8E4DGV1,0209688726,{'Color:': ' Blue'},noe,It sucks barely picks up anything definitely n...,sucks,1524096000,NaN,NaN
2,1,True,"04 16, 2018",A1NX8HM89FRQ32,0209688726,{'Color:': ' Black'},Eduard,"Well to write a short one, it blew 2 fuses of ...",Defective,1523836800,NaN,NaN
3,3,True,"04 13, 2018",A1X77G023NY0KY,0209688726,{'Color:': ' CA'},Lauren,I have absolutely no memory of buying this but...,Looks cool! Probably works,1523577600,NaN,NaN
4,5,True,"04 8, 2018",A3GK37JO2MGW6Q,0209688726,{'Color:': ' Black'},danny,it ok it does it job,Five Stars,1523145600,NaN,NaN


In [218]:
print(df['reviewText'][0])

After I wrote the below review, the manufacturer contacted me and explained how to use this.  Instead of the (current) picture on Amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally.  Then the charge / sync cable goes through the hole and you can charge from the side.  When used in landscape position this stand does make more sense so I'm upgrading this review from 2 stars to 4 stars (which I rarely do, but in this case user error) with a star off for lack of documentation.  Manufacturer has said he will include directions and I would also encourage him to update the photos on Amazon with more examples of how this can be used.  The wood quality is indeed good and it's a sturdy little stand.  I'm trying to think of when I'd actually use this stand... perhaps for Facetime chats.  I also think it would be useful for someone in an open office environment if they want to keep their phone on their desk and see alerts / notifications easi

2. Next, let's follow some steps to normalize the text data.

When dealing with natural language, it is important to notice that while, for example, the words "Copper" and "copper" are represented by two different strings, they have the same meaning. When applying statistical methods on this data, it is useful to ensure that words with the same meaning are represented by the same string.

* <span style="background-color: #ccfff2">Downcasing</span>: Let's first downcase the contents of the <span style="background-color: #ccfff2">reviewText</span> field.

Now the first review should be:

*'after i wrote the below review, the manufacturer contacted me and explained how to use this.  instead of the (current) picture on amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally.'*

In [219]:
df['reviewText'] = df['reviewText'].str.lower()

print(df['reviewText'][0])

after i wrote the below review, the manufacturer contacted me and explained how to use this.  instead of the (current) picture on amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally.  then the charge / sync cable goes through the hole and you can charge from the side.  when used in landscape position this stand does make more sense so i'm upgrading this review from 2 stars to 4 stars (which i rarely do, but in this case user error) with a star off for lack of documentation.  manufacturer has said he will include directions and i would also encourage him to update the photos on amazon with more examples of how this can be used.  the wood quality is indeed good and it's a sturdy little stand.  i'm trying to think of when i'd actually use this stand... perhaps for facetime chats.  i also think it would be useful for someone in an open office environment if they want to keep their phone on their desk and see alerts / notifications easi

3. Let's continue with punctuation and stop word removal. Stop words are words like "and", "the", etc. They are usually very common words that have little to do with the actual content matter. There's plenty openly available lists of stop words for almost any (natural) language.

* <span style="background-color: #ccfff2">Punctuation and stop-word removal</span>: Let's now remove all punctuation, as well as the stop words. You can find a stop word list for English, e.g. [here](https://gist.github.com/xldrkp/4a3b1a33f10d37bedbe0068f2b4482e8#file-stopwords-en-txt).*(use the link to download a txt of english stopwords)* Save the stopwords in the file as "stopwords-en.txt".

First review at this point reads as: 

*'wrote review manufacturer contacted explained current picture amazon phone vertically stand phone horizontally'*

In [220]:
stop_words = set()
with open('stopwords-en.txt') as f:
    for line in f:
        stop_words.add(line.strip())
print(len(stop_words))

df['reviewText'] = df['reviewText'].fillna('')
df['reviewText'] = df['reviewText'].apply(lambda x: ' '.join([w for w in (word.strip(',.!?()\n') for word in x.split ()) if w not in stop_words]))
print(df['reviewText'][0])

#note that there wasnt words 'use' and 'instead' in the stopwords file, so the sentence looks different to model solution

319
wrote review manufacturer contacted explained use instead current picture amazon phone placed vertically actually use stand phone placed horizontally charge / sync cable goes hole charge used landscape position stand does make sense i'm upgrading review 2 stars 4 stars rarely case user error star lack documentation manufacturer said include directions encourage update photos amazon examples used wood quality good it's sturdy little stand i'm trying think i'd actually use stand facetime chats think useful open office environment want phone desk alerts / notifications easily hope updated review helps original review: throwing stand garbage it's crafted nice wood functional near tell does come instructions product description confusing english poorly translated chinese iphone sits stand just fine it's stand way plug plug -- stand blocks turn iphone plug just looks strange i'm sure hole stand supposed included plastic feet instructions affixed stand began wobble figure work thing post 

4. Let's continue with stemming. For example, while the words "swims" and "swim" are different strings, they both refer to swimming. [Stemming](https://en.wikipedia.org/wiki/Stemming) refers to the process of mapping words from their inflected form to their base form, for instance: swims -> swim.

* <span style="background-color: #ccfff2">Stemming</span>: Apply a stemmer on the paragraphs, so that inflected forms are mapped to the base form. For example, for Python the popular natural language toolkit [nltk](http://www.nltk.org/howto/stem.html) has an easy to use stemmer. In case you are using R, you can try the [Snowball stemmer](https://www.rdocumentation.org/packages/corpus/versions/0.10.2/topics/stem_snowball). You can find out how to install nltk from [here](https://www.nltk.org/install.html). It will take a while to run! So, grab a coffee and wait :D

Finally, after stemming: 

*'wrote review manufactur contact explain current pictur amazon phone vertic stand phone horizont'*

In [205]:
from nltk.stem import *

stemmer = PorterStemmer()

df['reviewText'] = df['reviewText'].apply(lambda x: ' '.join([stemmer.stem(word) for word in x.split()]))
print(df['reviewText'][0])

wrote review manufactur contact explain use instead current pictur amazon phone place vertic actual use stand phone place horizont charg / sync cabl goe hole charg use landscap posit stand doe make sens i'm upgrad review 2 star 4 star rare case user error star lack document manufactur said includ direct encourag updat photo amazon exampl use wood qualiti good it' sturdi littl stand i'm tri think i'd actual use stand facetim chat think use open offic environ want phone desk alert / notif easili hope updat review help origin review: throw stand garbag it' craft nice wood function near tell doe come instruct product descript confus english poorli translat chines iphon sit stand just fine it' stand way plug plug -- stand block turn iphon plug just look strang i'm sure hole stand suppos includ plastic feet instruct affix stand began wobbl figur work thing post review far i'm concern box experi terribl sorri recommend sampl provid exchang honest review


5. Finally, filter the data by selecting reviews where the field <span style="background-color: #ccfff2">overall</span> is 4 or 5, and store the review texts in a file named <span style="background-color: #ccfff2">pos.txt</span>. Similarly, select reviews with rating 1 or 2 and store them in a file named <span style="background-color: #ccfff2">neg.txt</span>. Ignore the reviews with overall rating 3. Each line in the two files should contain exactly one preprocessed review text without the rating.

In [206]:
positive = df.loc[(df['overall'] == 4) | (df['overall'] == 5), 'reviewText']
negative = df.loc[(df['overall'] == 1) | (df['overall'] == 2), 'reviewText']

with open('pos.text', 'w') as f:
    for r in positive:
        f.write(r + '\n')
        
with open('neg.text', 'w') as f:
    for r in negative:
        f.write(r + '\n')

## Exercise 3 | SQL basics

Next, let's take a refresher on the basics of SQL. In this exercise, you will be working on the simplified Northwind 2000 SQLite database. You can download the database from Kaggle [here](https://courses.mooc.fi/api/v0/files/course/f92ffc32-2dd4-421d-87f3-c48800422cc5/files/VEKX2bxGCDGyojG902gmYZTXCnrAQw.zip).

To test your SQL queries and complete the exercise, you can download and install SQLite if you don't yet have it installed.

Please write SQL queries for the tasks on the simplified Northwind 2000 SQLite database.

1. List the first name, last name, and hire date of all employees hired after January 1st, 1994.

2. Count how many orders each customer has placed.

3. Find the names of all customers who have ordered the product "Chai".

4. Find all orders that have been placed but not yet shipped.

5. Find the customer who has placed the most orders.

In [207]:
import sqlite3 
database = 'db/northwind2000-simplified.sqlite'
conn = sqlite3.connect(database) 
c = conn.cursor() 
query = " SELECT FirstName, LastName, HireDate FROM Employees WHERE HireDate > '1994-01-01'; " 
c.execute(query)
rows = c.fetchall()
for row in rows:
    print(row)

('Robert', 'King', '1994-01-02')
('Laura', 'Callahan', '1994-03-05')
('Anne', 'Dodsworth', '1994-11-15')


In [208]:
query=" SELECT Customers.ContactName, count(Orders.CustomerID) FROM Customers JOIN Orders ON Orders.CustomerID = Customers.CustomerID GROUP BY Customers.CustomerID; "
c.execute(query)
rows = c.fetchall()
for row in rows:
    print(row)

('Maria Anders', 6)
('Ana Trujillo', 4)
('Antonio Moreno', 7)
('Thomas Hardy', 13)
('Christina Berglund', 18)
('Hanna Moos', 7)
('Frédérique Citeaux', 11)
('Martín Sommer', 3)
('Laurence Lebihan', 17)
('Elizabeth Lincoln', 14)
('Victoria Ashworth', 10)
('Patricio Simpson', 6)
('Francisco Chang', 1)
('Yang Wang', 8)
('Pedro Afonso', 5)
('Elizabeth Brown', 3)
('Sven Ottlieb', 6)
('Janine Labrune', 4)
('Ann Devon', 8)
('Roland Mendel', 30)
('Aria Cruz', 7)
('Martine Rancé', 5)
('Maria Larsson', 19)
('Peter Franken', 15)
('Carine Schmitt', 3)
('Paolo Accorti', 6)
('Lino Rodriguez', 8)
('Eduardo Saavedra', 5)
('José Pedro Freyre', 10)
('André Fonseca', 9)
('Howard Snyder', 11)
('Manuel Pereira', 2)
('Mario Pontes', 14)
('Carlos Hernández', 18)
('Yoshi Latimer', 5)
('Patricia McKenna', 19)
('Helen Bennett', 10)
('Philip Cramer', 14)
('Daniel Tonini', 4)
('Annette Roulet', 14)
('Yoshi Tannamuri', 3)
('John Steel', 2)
('Renate Messner', 15)
('Jaime Yorres', 4)
('Carlos González', 14)
('Felipe 

In [209]:
query=" SELECT Customers.ContactName FROM Customers JOIN Orders ON Customers.CustomerID = Orders.CustomerID JOIN OrderDetails ON Orders.OrderID = OrderDetails.OrderID JOIN Products ON OrderDetails.ProductID = Products.ProductID WHERE Products.ProductName = 'Chai'; " 
c.execute(query)
rows = c.fetchall()
for row in rows:
    print(row)

('Horst Kloss',)
('Paula Wilson',)
('Fran Wilson',)
('Rita Müller',)
('Guillermo Fernández',)
('Yang Wang',)
('Lúcia Carvalho',)
('Annette Roulet',)
('Isabel de Castro',)
('Renate Messner',)
('Pirkko Koskitalo',)
('Miguel Angel Paolino',)
('Jean Fresnière',)
('Janine Labrune',)
('Zbyszek Piestrzeniewicz',)
('Frédérique Citeaux',)
('Patricia McKenna',)
('Christina Berglund',)
('Horst Kloss',)
('Jose Pavarotti',)
('Felipe Izquierdo',)
('Simon Crowther',)
('Felipe Izquierdo',)
('Jose Pavarotti',)
('Carlos Hernández',)
('Hari Kumar',)
('Paula Parente',)
('José Pedro Freyre',)
('Elizabeth Lincoln',)
('Paula Parente',)
('Liu Wong',)
('Matti Karttunen',)
('Howard Snyder',)
('Pirkko Koskitalo',)
('Jose Pavarotti',)
('Pascale Cartrain',)
('Ann Devon',)
('Renate Messner',)


In [210]:
query = " SELECT OrderID FROM Orders WHERE ShippedDate IS NULL; "
c.execute(query)
rows = c.fetchall()
for row in rows:
    print(row)

(11008,)
(11019,)
(11039,)
(11040,)
(11045,)
(11051,)
(11054,)
(11058,)
(11059,)
(11061,)
(11062,)
(11065,)
(11068,)
(11070,)
(11071,)
(11072,)
(11073,)
(11074,)
(11075,)
(11076,)
(11077,)


In [211]:
query=" SELECT Customers.ContactName, count(Orders.CustomerID) FROM Customers JOIN Orders ON Orders.CustomerID = Customers.CustomerID GROUP BY Customers.CustomerID ORDER BY count(Orders.CustomerID) DESC LIMIT 1; "
c.execute(query)
rows = c.fetchall()
for row in rows:
    print(row)

('Jose Pavarotti', 31)


**Remember to submit your solutions. You can return this Jupyter notebook (.ipynb) or .py, .R, etc depending on your programming preferences. Remember to also submit your SQL queries. No need to submit the text files for the programming exercises.**